package io.github.zhanry.hometunnel.storage

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import io.github.zhanry.hometunnel.model.PersistedState
import io.github.zhanry.hometunnel.model.ServerProfile
import java.io.File
import java.security.InvalidAlgorithmParameterException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.json.Json
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/** Exercises AndroidKeyStore itself; a JVM cipher does not enforce its IV policy. */
@RunWith(AndroidJUnit4::class)
class SecureStateStoreTest {
    private val context = InstrumentationRegistry.getInstrumentation().targetContext
    private val directory = File(context.noBackupFilesDir, "home_tunnel")
    private val stateFile = File(directory, "state.enc")
    private val alias = "home_tunnel_android_state_v1"
    private val session = PersistedState(
        installId = "keystore-regression-install",
        username = "fixture-user",
        profile = ServerProfile(
            "https://console.example.test", "https://console.example.test/api/v1/",
            "tunnel.example.test", 7000, "tunnel.example.test",
        ),
        accessToken = "fixture-access-token",
        refreshToken = "fixture-refresh-token",
        accessExpiresAt = "2099-01-01T00:00:00Z",
    )

    @Before fun resetState() = runBlocking<Unit> { SecureStateStore(context).clear() }

    @After fun cleanState() = runBlocking<Unit> {
        SecureStateStore(context).clear()
        directory.listFiles()?.filter { it.name.startsWith("state.enc.damaged-") }?.forEach { it.delete() }
    }

    @Test fun loginStateSurvivesOpeningANewStoreWithTheExistingKey() = runBlocking {
        // Match keys already generated by 6.0.0, including failed login attempts.
        val existingKey = generateExistingKey()
        SecureStateStore(context).save(session)

        val restored = SecureStateStore(context).load()
        assertEquals(session, restored)
        assertTrue(restored.signedIn)
        assertCallerNonceIsRejected(existingKey)
        val bytes = stateFile.readBytes()
        assertFalse(bytes.decodeToString().contains(requireNotNull(session.refreshToken)))

        // The original key must still decrypt the new file: no silent key reset.
        val ivSize = bytes[4].toInt() and 0xff
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.DECRYPT_MODE, existingKey,
            GCMParameterSpec(128, bytes.copyOfRange(5, 5 + ivSize)))
        val plaintext = cipher.doFinal(bytes.copyOfRange(5 + ivSize, bytes.size))
        assertEquals(session, Json.decodeFromString<PersistedState>(plaintext.decodeToString()))
    }

    @Test fun repeatedSavesUseDifferentNoncesAndBothRemainReadable() = runBlocking {
        val store = SecureStateStore(context)
        store.save(session)
        val first = stateFile.readBytes()
        assertEquals(session, SecureStateStore(context).load())
        store.save(session)
        val second = stateFile.readBytes()
        assertEquals(session, SecureStateStore(context).load())
        val firstIv = first.copyOfRange(5, 5 + (first[4].toInt() and 0xff))
        val secondIv = second.copyOfRange(5, 5 + (second[4].toInt() and 0xff))
        assertFalse(firstIv.contentEquals(secondIv))
    }

    @Test fun rotatingSessionTokensPersistsThroughTheUncachedUpdatePath() = runBlocking {
        SecureStateStore(context).save(session)
        val renewed = session.copy(accessToken = "renewed-access", refreshToken = "renewed-refresh")
        assertEquals(renewed, SecureStateStore(context).update { current ->
            assertEquals(session, current)
            current.copy(accessToken = renewed.accessToken, refreshToken = renewed.refreshToken)
        })
        assertEquals(renewed, SecureStateStore(context).load())
    }

    @Test fun existingVersionOneEnvelopeCanStillBeReadAndUpdated() = runBlocking {
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, generateExistingKey())
        val plaintext = Json.encodeToString(PersistedState.serializer(), session).encodeToByteArray()
        val ciphertext = cipher.doFinal(plaintext)
        assertTrue(directory.exists() || directory.mkdirs())
        stateFile.writeBytes(byteArrayOf(0x48, 0x54, 0x41, 1, cipher.iv.size.toByte()) + cipher.iv + ciphertext)

        assertEquals(session, SecureStateStore(context).load())
        val updated = SecureStateStore(context).update { it.copy(userDisplayName = "Restored account") }
        assertEquals("Restored account", updated.userDisplayName)
        assertEquals(updated, SecureStateStore(context).load())
    }

    @Test fun modifiedCiphertextIsRejectedAndPreservedForRecovery() = runBlocking {
        SecureStateStore(context).save(session)
        val modified = stateFile.readBytes().also { it[it.lastIndex] = (it.last().toInt() xor 1).toByte() }
        stateFile.writeBytes(modified)
        val result = runCatching { SecureStateStore(context).load() }
        assertTrue(result.exceptionOrNull() is StateUnavailableException)
        assertFalse(stateFile.exists())
        assertTrue(directory.listFiles().orEmpty().any {
            it.name.startsWith("state.enc.damaged-") && it.readBytes().contentEquals(modified)
        })
    }

    @Test fun signingInAfterLogoutGeneratesAWorkingProtectedKey() = runBlocking {
        val store = SecureStateStore(context)
        store.save(session)
        store.clear()
        val keys = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        assertFalse(keys.containsAlias(alias))
        assertFalse(SecureStateStore(context).load().signedIn)
        store.save(session)
        assertEquals(session, SecureStateStore(context).load())
        assertCallerNonceIsRejected(keys.getKey(alias, null) as SecretKey)
    }

    private fun generateExistingKey(): SecretKey =
        KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore").run {
            init(KeyGenParameterSpec.Builder(alias, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .setRandomizedEncryptionRequired(true)
                .build())
            generateKey()
        }

    private fun assertCallerNonceIsRejected(key: SecretKey) {
        val failure = runCatching {
            Cipher.getInstance("AES/GCM/NoPadding").init(Cipher.ENCRYPT_MODE, key, GCMParameterSpec(128, ByteArray(12)))
        }.exceptionOrNull()
        assertTrue("The key must require a provider-generated encryption nonce", failure is InvalidAlgorithmParameterException)
    }
}
